name: Create a pull request when pushed new branch.

# Set trigger when pushed branches
on:
  push:
    branches:
      - "features/**"
      - "fix/**"
      - "setup/**"

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check if exists of pull request
        id: check_pr
        run: |
          pull_request_title=${{ github.ref_name }}
          base_branch="main"
          echo "::set-output name=count::$(gh pr list -S ${pull_request_title}' in:title' -B $base_branch | wc -l)"
          echo "::set-output name=pull_request_title::$pull_request_title"
          echo "::set-output name=base_branch::$base_branch"
      - name: Create new pull request
        if: ${{ steps.check_pr.outputs.count == 0 }}
        # head_branch_name -> main に対してpull request作成
        run: |
          head_branch=${{ github.ref_name }}
          gh pr create -B ${steps.check_pr.outputs.base_branch} -H ${head_branch} -t ${steps.check_pr.outputs.pull_request_title} -b "Auto created by github actions."
